# Generated by Django 2.2.2 on 2019-07-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districts',
            old_name='popularity_density',
            new_name='population_density',
        ),
    ]
